# Generated by Django 4.0 on 2022-01-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('s_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField()),
                ('can_attend', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('dietary_reqs', models.CharField(max_length=1000)),
                ('note', models.CharField(max_length=1000)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.guest')),
            ],
        ),
    ]
