# Generated by Django 4.0 on 2022-01-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attending',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='guest',
            name='dietary_reqs',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='has_plus1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='vegetarian',
            field=models.BooleanField(default=None),
        ),
    ]
