# Generated by Django 4.0 on 2022-01-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_guest_attending_guest_dietary_reqs_guest_has_plus1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='attending',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='vegetarian',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
