# Generated by Django 4.0 on 2022-02-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_alter_response_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='added_plus1',
            field=models.BooleanField(default=False),
        ),
    ]
