# Generated by Django 4.0 on 2022-02-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_guest_added_plus1'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
